apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: ${TESTING_IMAGE}  # Replaced by your GitHub Action step with the image from ghcr.io
          ports:
            - containerPort: 8888  # Make sure this matches your application's exposed port
          env:
            - name: ENV_VAR_EXAMPLE  # Example of environment variable (you can customize it)
              value: "value"
      imagePullSecrets:
        - name: regcred  # Ensure the secret is created to pull from ghcr.io
