name: Build and Deploy 04

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      security-events: write

    steps:

        - name: Checkout git repo
          uses: actions/checkout@v3

        - name: Docker meta
          id: docker_meta
          uses: docker/metadata-action@v3
          with:
            images: alvargran/httpenv
            flavor:
              latest=false
            tags: |
              type=raw,value=04
              type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
              type=ref,event=pr
              type=ref,event=branch
              type=semver,pattern={{version}}

        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v1 
        
        - name: Set Up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Docker build
          uses: docker/build-push-action@v2
          with:
            push: true  # Removed "load: true" to allow pushing multi-platform images
            tags: |
              alvargran/httpenv:latest
              alvargran/httpenv:04
              alvargran/httpenv:${{ github.run_id }}
            labels: ${{ steps.docker_meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            platforms: linux/amd64,linux/arm64,linux/arm/v7

        - name: Run Trivy for all CVEs (non blocking)
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: alvargran/httpenv:${{ github.run_id }}
            exit-code: 0
            format: table

        - name: Run Trivy for HIGH, CRITICAL CVEs and report (blocking)
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: alvargran/httpenv:${{ github.run_id }}  # Reference the pushed image
            exit-code: 1
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'HIGH,CRITICAL'
            format: 'sarif'
            output: 'trivy-results.sarif'

        # Check if the SARIF file was generated
        - name: Verify SARIF File Creation
          run: ls -la trivy-results.sarif

        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          if: always()
          with:
            sarif_file: 'trivy-results.sarif'

        - name: Find Comment for image tags
          uses: peter-evans/find-comment@v1
          if: github.event_name == 'pull_request'
          id: fc
          with:
            issue-number: ${{ github.event.pull_request.number }}
            comment-author: 'github-actions[bot]'
            body-includes: Docker image tag(s) pushed

        - name: Create or update comment for image tag
          uses: peter-evans/create-or-update-comment@v1
          if: github.event_name == 'pull_request'
          with:
            comment-id: ${{ steps.fc.outputs.comment-id }}
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              Docker image tag(s) pushed:
              ´´´text
              ${{ steps.docker_meta.outputs.tags }}
              ´´´

              Labels added to images:
              ```text
              ${{ steps.docker_meta.outputs.labels }}
              ```
            edit-mode: replace
