name: Build and Deploy 04

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Docker meta
          id: docker_meta
          uses: docker/metadata-action@v3
          with:
            images: alvargran/httpenv
            flavor:
              latest=false
            tags: |
              type=raw,value=04
              type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
              type=ref,event=pr
              type=ref,event=branch
              type=semver,pattern={{version}}

        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v1 
        
        - name: Set Up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Docker build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ steps.docker_meta.outputs.tags }}
            labels: ${{ steps.docker_meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            platforms: linux/amd64,linux/arm64,linux/arm/v7