on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}

      - name: Clone repository over SSH
        run: git clone git@github.com:Alluxu/httpenv.git

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: alvargran/httpenv:latest,alvargran/httpenv:01

