services:
  httpenv:
    image: "${TESTING_IMAGE}"
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 30s

  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      postgres:
        condition: service_healthy
    command: curl --fail http://httpenv:8888 || exit 1