name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Set Up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v1 

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Docker build
          uses: docker/build-push-action@v2
          with:
            push: ${{ github.event_name != 'pull_request' }}
            tags: alvargran/httpenv:latest,alvargran/httpenv:01

            cache-from: type=gha
            cache-to: type=gha,mode=max
            platforms: linux/amd64,linux/arm64,linux/arm/v7

